### ISSUE TITLE
Update for the latest Roboto?

### ISSUE THREAD

**Issue by jensck** [andreasf/Roboto#1]
Roboto just got another major revision with the release of the Android L preview.  Any chance we'll see an update to this project, too?

**Comment by andreasf** [comment]
Oh, a user! How exciting and unexpected ;-)

I just updated it with the current version from this page: http://www.google.com/design/spec/resources/roboto-font.html

The font mostly seems to work:
- In Inkscape 0.48, "Black" is called "Heavy", but apart from that everything works
- In Scribus 1.4.3 everything is OK
- In Libreoffice 4.2, "Medium" is not available, but "Medium Italic" is

**Comment by jensck** [comment]
Awesome, thanks!
